#!/opt/homebrew/bin/bash
# generated by prompts to GPT-4 

# Check if a directory argument was provided, otherwise default to the current directory
START_DIR="${1:-.}"

# Create an empty array to store directories containing .fits files
dirs=()

# Use find command to search down from the current directory for .fits files
while IFS= read -r -d '' dir; do
    # Store the directory part of the path into the dirs array
    dirs+=("$(dirname "$dir")")
done < <(find "$START_DIR" -type f -name "*.fits" -print0)

# Remove duplicate directories from the array
dirs=($(printf "%s\n" "${dirs[@]}" | sort -u))

# Call the python program for each directory in the dirs array
for dir in "${dirs[@]}"; do
    echo "python abscli.py -s \"$dir\""
    # python abscli.py -s "$dir"
done
